// DO NOT EDIT. generated by webtyp.com/ormc

package changelog

import (
	"webtyp.com/model"
	"webtyp.com/orm"
)

type Change struct {
	Version   int64
	TableName string
	RowId     string
	Op        string
}

func (m *Change) ModelName() string { return "change_log" }

func (m *Change) Schema() []model.Field { return ChangeModel.Fields }

func (m *Change) Pointers() []any { return []any{&m.Version, &m.TableName, &m.RowId, &m.Op} }

func (m *Change) IsNil() bool { return m == nil }

func (m *Change) EncodeFields(w model.FieldWriter) {
	w.Int("version", m.Version)
	w.String("table_name", m.TableName)
	w.String("row_id", m.RowId)
	w.String("op", m.Op)
}

func (m *Change) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("version"); ok {
		m.Version = v
	}
	if v, ok := r.String("table_name"); ok {
		m.TableName = v
	}
	if v, ok := r.String("row_id"); ok {
		m.RowId = v
	}
	if v, ok := r.String("op"); ok {
		m.Op = v
	}
}

type ChangeList []*Change

func (s *ChangeList) Len() int                         { return len(*s) }
func (s *ChangeList) At(i int) model.Fielder           { return (*s)[i] }
func (s *ChangeList) Append() model.Fielder            { v := &Change{}; *s = append(*s, v); return v }
func (s *ChangeList) IsNil() bool                      { return s == nil }
func (s *ChangeList) EncodeFields(_ model.FieldWriter) {}
func (s *ChangeList) DecodeFields(_ model.FieldReader) {}

func (m *Change) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Change_ = struct {
	Version   string
	TableName string
	RowId     string
	Op        string
}{
	Version:   "version",
	TableName: "table_name",
	RowId:     "row_id",
	Op:        "op",
}

func ReadOneChange(qb *orm.QB, model *Change) (*Change, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllChange(qb *orm.QB) (ChangeList, error) {
	var results ChangeList
	err := qb.ReadAll(
		func() model.Model { return &Change{} },
		func(m model.Model) { results = append(results, m.(*Change)) },
	)
	return results, err
}
